version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sns-pulish-sample07"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-s7ts04woxm1l"
s3_prefix = "sns-pulish-sample07"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SNSTopicName=\"mpf\""
